FROM bitnami/spark:3.0.0

USER root

RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.0.0/spark-sql-kafka-0-10_2.12-3.0.0.jar --output /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.0.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.6.0/kafka-clients-2.6.0.jar --output /opt/bitnami/spark/jars/kafka-clients-2.6.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-streaming-kafka-0-10_2.12/3.0.0/spark-streaming-kafka-0-10_2.12-3.0.0.jar --output /opt/bitnami/spark/jars/spark-streaming-kafka-0-10_2.12-3.0.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.0.0/spark-token-provider-kafka-0-10_2.12-3.0.0.jar --output /opt/bitnami/spark/jars/spark-token-provider-kafka-0-10_2.12-3.0.0.jar
RUN curl https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.8.1/commons-pool2-2.8.1.jar --output /opt/bitnami/spark/jars/commons-pool2-2.8.1.jar
RUN curl https://repo1.maven.org/maven2/com/datastax/spark/spark-cassandra-connector-assembly_2.12/3.0.0/spark-cassandra-connector-assembly_2.12-3.0.0.jar --output /opt/bitnami/spark/jars/spark-cassandra-connector-assembly_2.12-3.0.0.jar

RUN  apt-get update \
  && apt-get install -y wget gnupg2 ffmpeg libsm6 libxext6

COPY requirements-gpu.txt /opt/bitnami/python/requirements-gpu.txt
RUN pip install -r /opt/bitnami/python/requirements-gpu.txt

RUN echo "deb http://deb.debian.org/debian buster-backports main contrib non-free" >> /etc/apt/sources.list
RUN echo "deb http://deb.debian.org/debian experimental main non-free" >> /etc/apt/sources.list
RUN apt-get update

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
RUN dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
RUN apt-get update
RUN wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
RUN apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
RUN apt-get update

RUN apt-get install libcudnn7=7.6.5.32-1+cuda10.0 libcudnn7-dev=7.6.5.32-1+cuda10.0
RUN apt-get update

RUN apt-get install -y cuda-toolkit-10-0

USER 1001
